### ISSUE TITLE
help  thankx

### ISSUE THREAD

**Issue by ALLIYDING** [BogdanCodreanu/obsidian-moc-link-helper#1]
![Snipaste_2024-11-12_07-47-13](https://github.com/user-attachments/assets/33be5bc6-7898-4aba-a9cc-7ecd5d57cf35)
all i view like this。can you tell me  all to do next? thanx

**Comment by BogdanCodreanu** [comment]
Hi. This is shown when the note is considered a "child" note, instead of a "parent note". If you want it to be viewed as a parent note, you need to tag the note with MOC. Like this 
![image](https://github.com/user-attachments/assets/dacb04d5-5cdf-4c80-b6fa-6fbdbec884c7)

The tag "parent tag name" can also be changed in the settings, if you're not using "MOC" tag in your vault.
